export const FETCH_ACC_ENTRY_TYPE = "FETCH_ACC_ENTRY_TYPE";
export const FETCH_ACC_ENTRY_TYPE_SUCCESS = "FETCH_ACC_ENTRY_TYPE_SUCCESS";
export const FETCH_ACC_ENTRY_TYPE_FAILURE = "FETCH_ACC_ENTRY_TYPE_FAILURE";

export const UPDATE_ACC_ENTRY_TYPE = "FETCH_ACC_ENTRY_TYPE";
export const UPDATE_ACC_ENTRY_TYPE_SUCCESS = "FETCH_ACC_ENTRY_TYPE_SUCCESS";
export const UPDATE_ACC_ENTRY_TYPE_FAILURE = "FETCH_ACC_ENTRY_TYPE_FAILURE";