export const FETCH_ACCOUNT_BOOK = "FETCH_ACCOUNT_BOOK";
export const FETCH_ACCOUNT_BOOK_SUCCESS = "FETCH_ACCOUNT_BOOK_SUCCESS";
export const FETCH_ACCOUNT_BOOK_FAILURE = "FETCH_ACCOUNT_BOOK_FAILURE";

export const FETCH_SUM_ACCOUNT_BOOK = "FETCH_SUM_ACCOUNT_BOOK";
export const FETCH_SUM_ACCOUNT_BOOK_SUCCESS = "FETCH_SUM_ACCOUNT_BOOK_SUCCESS";
export const FETCH_SUM_ACCOUNT_BOOK_FAILURE = "FETCH_SUM_ACCOUNT_BOOK_FAILURE";
