export const FETCH_BILL = "FETCH_BILL";
export const FETCH_BILL_SUCCESS = "FETCH_BILL_SUCCESS";
export const FETCH_BILL_FAILURE = "FETCH_BILL_FAILURE";

export const FETCH_SUM_BILL = "FETCH_SUM_BILL";
export const FETCH_SUM_BILL_SUCCESS = "FETCH_SUM_BILL_SUCCESS";
export const FETCH_SUM_BILL_FAILURE = "FETCH_SUM_BILL_FAILURE";

export const FETCH_FILTER_BILL = "FETCH_FILTER_BILL";
export const FETCH_FILTER_BILL_SUCCESS = "FETCH_FILTER_BILL_SUCCESS";
export const FETCH_FILTER_BILL_FAILURE = "FETCH_FILTER_BILL_FAILURE";
