export const FETCH_CARD_CUSTOMER = "FETCH_CARD_CUSTOMER";
export const FETCH_CARD_CUSTOMER_SUCCESS = "FETCH_CARD_CUSTOMER_SUCCESS";

export const FETCH_ALL_CARD = "FETCH_ALL_CARD";
export const FETCH_ALL_CARD_SUCCESS = "FETCH_ALL_CARD_SUCCESS";

export const FETCH_CREATE_CARD_CUSTOMER = "FETCH_CREATE_CARD_CUSTOMER";
export const FETCH_CREATE_CARD_CUSTOMER_SUCCESS = "FETCH_CREATE_CARD_CUSTOMER_SUCCESS";
export const FETCH_CREATE_CARD_CUSTOMER_FAILURE  = "FETCH_CREATE_CARD_CUSTOMER_FAILURE";
