export const FETCH_SEARCH_CUSTOMER = "FETCH_SEARCH_CUSTOMER";
export const FETCH_SEARCH_CUSTOMER_SUCCESS = "FETCH_SEARCH_CUSTOMER_SUCCESS";

export const FETCH_All_CUSTOMER = "FETCH_All_CUSTOMER";
export const FETCH_ALL_CUSTOMER_SUCCESS = "FETCH_ALL_CUSTOMER_SUCCESS";
export const FETCH_All_CUSTOMER_FAILURE = "FETCH_All_CUSTOMER_FAILURE";
