export const FETCH_EMP = "FETCH_EMP";
export const FETCH_EMP_SUCCESS = "FETCH_EMP_SUCCESS";
export const FETCH_EMP_FAILURE = "FETCH_EMP_FAILURE";

export const FETCH_CREATE_EMP = "FETCH_CREATE_EMP";
export const FETCH_CREATE_EMP_SUCCESS = "FETCH_CREATE_EMP_SUCCESS";
export const FETCH_CREATE_EMP_FAILURE = "FETCH_CREATE_EMP_FAILURE";
