export const FETCH_GEN_ACCOUNT_BOOK = "FETCH_GEN_ACCOUNT_BOOK";
export const FETCH_GEN_ACCOUNT_BOOK_SUCCESS = "FETCH_GEN_ACCOUNT_BOOK_SUCCESS";
export const FETCH_GEN_ACCOUNT_BOOK_FAILURE = "FETCH_GEN_ACCOUNT_BOOK_FAILURE";

export const FETCH_GEN_SUM_ACCOUNT_BOOK = "FETCH_GEN_SUM_ACCOUNT_BOOK";
export const FETCH_GEN_SUM_ACCOUNT_BOOK_SUCCESS = "FETCH_GEN_SUM_ACCOUNT_BOOK_SUCCESS";
export const FETCH_GEN_SUM_ACCOUNT_BOOK_FAILURE = "FETCH_GEN_SUM_ACCOUNT_BOOK_FAILURE";
