export const FETCH_INVOICE = "FETCH_INVOICE";
export const FETCH_INVOICE_SUCCESS = "FETCH_INVOICE_SUCCESS";
export const FETCH_INVOICE_FAILURE = "FETCH_INVOICE_FAILURE";

export const FETCH_POS ="FETCH_POS";
export const FETCH_POS_SUCCESS="FETCH_POS_SUCCESS";