export const FETCH_INVOICE = "FETCH_INVOICE";
export const FETCH_INVOICE_SUCCESS = "FETCH_INVOICE_SUCCESS";
export const FETCH_INVOICE_FAILURE = "FETCH_INVOICE_FAILURE";

export const FETCH_SUM_INVOICE = "FETCH_SUM_INVOICE";
export const FETCH_SUM_INVOICE_SUCCESS = "FETCH_SUM_INVOICE_SUCCESS";
export const FETCH_SUM_INVOICE_FAILURE = "FETCH_SUM_INVOICE_FAILURE";

export const FETCH_CREATE_INVOICE = "FETCH_CREATE_INVOICE";
export const FETCH_CREATE_INVOICE_SUCCESS = "FETCH_CREATE_INVOICE_SUCCESS";
export const FETCH_CREATE_INVOICE_FAILURE = "FETCH_CREATE_INVOICE_FAILURE";

export const FETCH_POS ="FETCH_POS";
export const FETCH_POS_SUCCESS="FETCH_POS_SUCCESS";